In [78]:
import pymupdf
import numpy as np
from sentence_transformers import SentenceTransformer
import ollama
import pandas as pd 

pdf_path = r"C:\Users\Asutosh\OneDrive\Documents\HOI ML codes\RAG\Impact of phase lag on synchronization.pdf"
pdf = pymupdf.open(pdf_path)

print(f"Number of pages in the pdf: {len(pdf)}")

Number of pages in the pdf: 7

In [79]:
#page extraction 

pages = []

for page_num, page in enumerate(pdf):
    text = page.get_text()
    pages.append({
        "page": page_num + 1,
        "text": text
    })

print(f"Pages extracted: {len(pages)}")
print(f"{pages[0]['text'][:4000]}")
print(f"{pages[1]['text'][:4000]}")

Pages extracted: 7
PHYSICAL REVIEW E 108, 034208 (2023)
Impact of phase lag on synchronization in frustrated Kuramoto model
with higher-order interactions
Sangita Dutta,1,* Abhijit Mondal,1 Prosenjit Kundu
,2,† Pitambar Khanra
,3,‡ Pinaki Pal,1,§ and Chittaranjan Hens4
1Department of Mathematics, National Institute of Technology, Durgapur 713209, India
2Dhirubhai Ambani Institute of Information and Communication Technology, Gandhinagar, Gujarat 382007, India
3Department of Mathematics, State University of New York at Buffalo, Buffalo 14260, USA
4Center for Computational Natural Science and Bioinformatics, International Institute of Informational Technology,
Gachibowli, Hyderabad 500032, India
(Received 4 May 2023; accepted 25 August 2023; published 18 September 2023)
The study of ﬁrst order transition (explosive synchronization) in an ensemble (network) of coupled oscillators
has been the topic of paramount interest among the researchers for more than one decade. Several frameworks
have been proposed to induce explosive synchronization in a network and it has been reported that phase
frustration in a network usually suppresses ﬁrst order transition in the presence of pairwise interactions among
the oscillators. However, on the contrary, by considering networks of phase frustrated coupled oscillators in
the presence of higher-order interactions (up to 2-simplexes) we show here, under certain conditions, phase
frustration can promote explosive synchronization in a network. A low-dimensional model of the network in
the thermodynamic limit is derived using the Ott-Antonsen ansatz to explain this surprising result. Analytical
treatment of the low-dimensional model, including bifurcation analysis, explains the apparent counter intuitive
result quite clearly.
DOI: 10.1103/PhysRevE.108.034208
I. INTRODUCTION
Synchronization [1–3] is a captivating phenomenon ob-
served in natural and artiﬁcial systems [4–14]. A large set
of coupled oscillators undergoes a continuous synchroniza-
tion transition if the interaction strength among themselves
is gradually increased. To describe such transition, a sim-
ple and analytically tractable phase model was developed by
Yoshiki Kuramoto [10], in which each oscillator has its own
intrinsic frequency (ωi), and cross-talks to each other via a
periodic coupling function representing pairwise interactions.
The phase of the ith oscillator is given by
˙θi = ωi + K
N

j=1
sin(θj −θi),
i = 1, 2, . . . , N,
(1)
where K is the coupling strength and θi is the phase of the ith
oscillator. To measure the level of synchronization, the order
parameter r is deﬁned as
reiψ = 1
N
N

j=1
eiθ j.
(2)
The classical Kuramoto model (KM) [10,15] described above
shows second order (continuous)
or ﬁrst order (explosive)
*sangitaduttaprl@gmail.com
†jitprosen.math@gmail.com
‡pitambar.khanra89@gmail.com
§pinaki.pal@maths.nitdgp.ac.in
transition to synchronization (r →1) state depending on the
choice of natural frequencies, as the coupling strength is
gradually increased from a small value. In general, it shows
second order transition for unimodal frequency distributions
[2], whereas ﬁrst order transition is observed for uniform or
bimodal distribution of frequencies [16,17,19]. All the oscilla-
tors rotate with the mean of the natural frequencies in a higher
coupling strength. However, different scenarios may appear
if a phase-lag or frustration parameter (β) [13,18–27] is in-
troduced in the pairwise coupling function [sin(θj −θi −β)].
This phase-lag parameter shifts the system’s synchronous fre-
quency from the mean natural frequency. Thus, β can be
used as a control parameter that can tune the mean frequency
to a desired one [24]. The model was ﬁrst introduced by
Sakaguchi jointly with Kuramoto and is presently known as
the Sakaguchi-Kuramoto (SK) model. In the SK model, the
phase lag β generally opposes the coupled system to reach
to the global synchronous state and consequently, higher cou-
pling strength compared to KM is required for achie
SANGITA DUTTA et al.
PHYSICAL REVIEW E 108, 034208 (2023)
FIG. 1. Schematic diagram of a simplicial complex consisting of
0-simplex (circles), 1-simplex (edges), and 2-simplex (triangles).
Note that models of Josephson junction arrays [13], power
network systems [27], dynamics of mechanical rotors [36],
quantum networks [26] all can be captured by such phase-lag
oscillators under the paradigm of pairwise interactions.
However, in recent studies the importance of incorporating
higher-order interactions (HOI) along with its pairwise coun-
terpart has been emphasized [37–50]. Speciﬁcally, the works
on neuroscience [45–47,51], ecology [52–55] and physics
[56] have highlighted the crucial role of such higher-order
interactions (e.g., in a collaboration network multiauthor
collaboration [57]) in addition to pairwise one. Simplicial
complexes [58,59] can successfully encode these higher-order
structures. An n simplex is formed by (n + 1) interacting
units, consisting of all the d (< n) simplexes. For example, 1-
simplex denotes the pairwise interactions, 2-simplex denotes
the three way interactions, including pairwise one, and so on.
These simplices adhere to one another along their sides, and
form a simplicial complex. Figure 1 represents a schematic
diagram of a simplicial complex with higher-order interac-
tions. Until now some of the dynamical behaviors induced by
the HOI have been explored including multistability [60,61],
chimera states [62], chaos [63], etc. Also, it has been shown
that the presence of HOI along with pairwise interactions can
produce high levels of synchronization in weaker coupling
strength [64] and may lead to the ﬁrst order or discontinuous
transition to desynchronization [60]. Recently, Skardal et al.
has reported in [65] that the HOI in a simplicial complex
can exhibit abrupt transition to synchrony, without any de-
gree frequency correlation. Subsequently, in [66], it has been
demonstrated that adaptation to higher-order coupling leads
to tired synchronization transition in addition to second order
transition.
In this paper, we consider the SK model with HOI under
the all-to-all coupling conﬁguration and observe a signiﬁ-
cantly different effect of phase frustration compared to the
ones observed in the presence of solely pairwise interac-
tions. For simplicity we restrict ourselves toward pairwise
and triadic interactions only. It is observed that instead of
inhibiting discontinuous transition to synchronization, phase -
lag promotes it in certain regions of the parameter space in the
presence of HOI. This surprising result is explained based on
an analytical framework based on Ott-Antonsen anastz [67].
II. MODEL DESCRIPTION AND NUMERICAL
SIMUATIONS
The dynamics of a phase frustrated undirected simplicial
complex of N number of nodes with global connectivity is
governed by the following system of equations:
˙θi = ωi + K1
N
N

j=1
sin(θj −θi −β)
+ K2
N2
N

j=1
N

l=1
sin(2θj −θl −θi −β),
i = 1, 2, . . . , N.
(3)
This is the generalization of the classical Sakaguchi-
Kuramoto model obtained by incorporating HOI along with
pairwise ones. Here θi represents the phase and ωi is the
natural frequency of the ith oscillator, and ω is drawn
from a Lorentzian distribution with density function g(ω) =

π[2+(ω−ω0)2] with mean ω0. β denotes the uniform phase -lag
of the system. K1 and K2 are the coupling strengths of pairwise
interactions and HOI, respectively. Two complex order param-
eters associated with 1-simplex and 2-simplex are deﬁned by
z = reiψ = 1
N
N

j=1
eiθj,
z2 = r2eiψ2 = 1
N
N

j=1
e2iθj,
(4)
where the amplitudes r = |z| and r2 = |z2| of the order
parameters z and z2, respectively, measures the level of syn-
chronization, and ψ and ψ2 are the respective arguments,
representing the average phases of the oscillators.
To ﬁnd the effect of the phase frustration on the SK model
with HOI, we simulate the equations (3) with network size
N = 103 by the fourth order Runge-Kutta method with time
step δt =

In [80]:
#embedding 

model = SentenceTransformer('all-MiniLM-L6-v2')
tokenizer = model.tokenizer

#chunking 
chunk_size = 120
chunk_overlap = 12

#chunks stored in a list here 
chunks = []

chunk_id = 0
for page_data in pages:
    page_number = page_data["page"]
    text = page_data["text"]

    #converting page text into token IDs
    token_ids = tokenizer.encode(text,
                                 add_special_tokens = False, truncation=False, verbose=False)

    start = 0

    while start < len(token_ids):
        end = start + chunk_size 

        chunk_token_ids = token_ids[start:end]
        chunk_text = tokenizer.decode(chunk_token_ids, skip_special_tokens = True)

        chunks.append({
            "chunk_id": chunk_id,
            "page": page_number,
            "text" : chunk_text, 
            "token_count": len(chunk_token_ids)       
        })

        chunk_id += 1

        #stopping conditon 
        if end >= len(token_ids):
            break
        #moving forward 
        start += chunk_size - chunk_overlap

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [81]:
chunks[0]

{'chunk_id': 0,
 'page': 1,
 'text': 'physical review e 108, 034208 ( 2023 ) impact of phase lag on synchronization in frustrated kuramoto model with higher - order interactions sangita dutta, 1, * abhijit mondal, 1 prosenjit kundu, 2, † pitambar khanra, 3, ‡ pinaki pal, 1, § and chittaranjan hens4 1department of mathematics, national institute of technology, durgapur 713209, india 2dhirubhai ambani institute of information and communication technology, gandhinagar, gujarat',
 'token_count': 120}

In [82]:
print(f"Total number of chunks created: {len(chunks)}")

Total number of chunks created: 93

In [83]:
for chunk in chunks:
    print(f"Chunk ID: {chunk['chunk_id']}, Page: {chunk['page']}, Text: {chunk['text'][:100]}...")

Chunk ID: 0, Page: 1, Text: physical review e 108, 034208 ( 2023 ) impact of phase lag on synchronization in frustrated kuramoto...
Chunk ID: 1, Page: 1, Text: ##i institute of information and communication technology, gandhinagar, gujarat 382007, india 3depar...
Chunk ID: 2, Page: 1, Text: oscillators has been the topic of paramount interest among the researchers for more than one decade....
Chunk ID: 3, Page: 1, Text: , phase frustration can promote explosive synchronization in a network. a low - dimensional model of...
Chunk ID: 4, Page: 1, Text: - served in natural and artiﬁcial systems [ 4 – 14 ]. a large set of coupled oscillators undergoes a...
Chunk ID: 5, Page: 1, Text: interactions. the phase of the ith oscillator is given by = ωi + k n j = 1 sin ( θj −θi ), i = 1, 2,...
Chunk ID: 6, Page: 1, Text: kuramoto model ( km ) [ 10, 15 ] described above shows second order ( continuous ) or ﬁrst order ( e...
Chunk ID: 7, Page: 1, Text: increased from a small value. in general, it shows second order transition for unimodal frequency di...
Chunk ID: 8, Page: 1, Text: [ sin ( θj −θi −β ) ]. this phase - lag parameter shifts the system ’ s synchronous fre - quency fro...
Chunk ID: 9, Page: 1, Text: the coupled system to reach to the global synchronous state and consequently, higher cou - pling str...
Chunk ID: 10, Page: 1, Text: [ 30 ]. even over a critical β, where the natural frequencies are correlated with degree, the hys - ...
Chunk ID: 11, Page: 1, Text: / 034208 ( 7 ) 034208 - 1 ©2023 american physical society...
Chunk ID: 12, Page: 2, Text: sangita dutta et al. physical review e 108, 034208 ( 2023 ) fig. 1. schematic diagram of a simplicia...
Chunk ID: 13, Page: 2, Text: ##tors under the paradigm of pairwise interactions. however, in recent studies the importance of inc...
Chunk ID: 14, Page: 2, Text: ##wise one. simplicial complexes [ 58, 59 ] can successfully encode these higher - order structures....
Chunk ID: 15, Page: 2, Text: ##hematic diagram of a simplicial complex with higher - order interac - tions. until now some of the...
Chunk ID: 16, Page: 2, Text: to desynchronization [ 60 ]. recently, skardal et al. has reported in [ 65 ] that the hoi in a simpl...
Chunk ID: 17, Page: 2, Text: ##guration and observe a signiﬁ - cantly different effect of phase frustration compared to the ones ...
Chunk ID: 18, Page: 2, Text: 67 ]. ii. model description and numerical simuations the dynamics of a phase frustrated undirected s...
Chunk ID: 19, Page: 2, Text: this is the generalization of the classical sakaguchi - kuramoto model obtained by incorporating hoi...
Chunk ID: 20, Page: 2, Text: interactions and hoi, respectively. two complex order param - eters associated with 1 - simplex and ...
Chunk ID: 21, Page: 2, Text: , and ψ and ψ2 are the respective arguments, representing the average phases of the oscillators. to ...
Chunk ID: 22, Page: 2, Text: ##tors are spread uniformly at random around a circle. the natural frequencies are drawn from a lore...
Chunk ID: 23, Page: 2, Text: k1 = 12 and continued until k1 = −1 by grad - ually decreasing k1 in small steps. note that, during ...
Chunk ID: 24, Page: 2, Text: and β = 1. 35 ( red ) for both forward and backward continuations. it is seen that the system exhibi...
Chunk ID: 25, Page: 3, Text: impact of phase lag on synchronization in … physical review e 108, 034208 ( 2023 ) 0 4 8 12 16 20 0 ...
Chunk ID: 26, Page: 3, Text: ##le of the global network for different phase - lag values. forward and backward transitions are in...
Chunk ID: 27, Page: 3, Text: k1 = 2. 5 for different β. the variation of the order parameter r with respect to k2 is pre - sented...
Chunk ID: 28, Page: 3, Text: cyan ), discontinuous transitions to synchronization are observed. therefore, it is clearly observed...
Chunk ID: 29, Page: 3, Text: this interesting result we proceed to derive a low - dimensional model ( ldm ) of the system ( 3 ) u...
Chunk ID: 30, Page: 3, Text: −ei ( θi + β ) ], ( 5 ) where h = k1z + and the overbar denotes complex conjugate. in the thermodyna...
Chunk ID: 31, Page: 3, Text: ∞ n = 1 [ fn ( ω, t ) einθ + c. c. ], ( 6 ) where c. c. denotes the complex conjugate and fn ( ω, t ...
Chunk ID: 32, Page: 3, Text: 0. 5 1 0 5 10 = 0 sn = 0. 8 ( c ) 2. 5 2. 5 ( d ) ( a ) ( b ) = 1 sn = 1. 318 fig. 3. bifurcation di...
Chunk ID: 33, Page: 3, Text: k2 for k1 = 2. 5 with β = 0 and 0. 8 respectively. solid and dashed lines are obtained from the ldm,...
Chunk ID: 34, Page: 3, Text: v = dθ dt is the velocity given by eq. ( 5 ). replacing f by its fourier series representation ( 6 )...
Chunk ID: 35, Page: 3, Text: ##i, t ) =. at ω = ω0 −i, eq. ( 8 ) leads to = izω0 −z + 1 2 [ ( k1z + ) e−iβ−z2 ( + ) eiβ ]. ( 9 ) ...
Chunk ID: 36, Page: 3, Text: ##1r + k2r3 ) [ 1 −r2 ], ( 10 ) = ω0 −sin β 2 ( k1 + k2r2 ) [ 1 + r2 ]. ( 11 ) the ldm is now used f...
Chunk ID: 37, Page: 3, Text: . first, we take k2 = 8 and construct the bifurcation diagrams for β = 1 and 1. 318 by varying k1. f...
Chunk ID: 38, Page: 4, Text: sangita dutta et al. physical review e 108, 034208 ( 2023 ) presented along with the stability infor...
Chunk ID: 39, Page: 4, Text: ##nta curve ) as a stable branch. thus, in the range 2. 9. 6 bistability is induced which is respons...
Chunk ID: 40, Page: 4, Text: pitchfork bifur - cation at k1 = 8 and a stable branch is originated ( solid green branch ) which le...
Chunk ID: 41, Page: 4, Text: and the trivial r = 0 branch ( dashed black line ) is always unstable in this case. on the other han...
Chunk ID: 42, Page: 4, Text: k2. 3. here, the sn bifurcation is responsible for the discontinuous transition to desynchronization...
Chunk ID: 43, Page: 4, Text: creased starting from 0, the system moves from discontinuous to continuous transition states with th...
Chunk ID: 44, Page: 4, Text: ##k1 ± ( k1 + k2 ) 2 −8k2 / cos β 2k2. ( 12 ) out of two nonzero equilibrium points given in ( 12 ),...
Chunk ID: 45, Page: 4, Text: ##2 ) 2 cos β = 8k2 ( 13 ) involving the parameters k1, k2 and β. thus, for any two given parameters...
Chunk ID: 46, Page: 4, Text: point marking the onset of continuous transition, which gives k1 = k2. using it in the equation ( 13...
Chunk ID: 47, Page: 4, Text: on the other hand, for ﬁxed k1, as β is increased, the completely opposite scenario occurs. the triv...
Chunk ID: 48, Page: 4, Text: easily checked that for = 1, k1 = 2. 5, and β < 0. 6435 only one nontrivial equilibrium point, i. e....
Chunk ID: 49, Page: 4, Text: ﬁxed points r + and r− will exist which marks the existence of bistability leading to discontinuous ...
Chunk ID: 50, Page: 4, Text: k2 = 8. the magenta curve indicates the backward transition or sn bifurcation points and the black c...
Chunk ID: 51, Page: 4, Text: uous paths [ see fig. 2 ( a ) ] only. at these forward transition points for different lag, the syst...
Chunk ID: 52, Page: 4, Text: from blue to maroon the value of the order parameter r increases from zero to one. the bistable regi...
Chunk ID: 53, Page: 5, Text: impact of phase lag on synchronization in … physical review e 108, 034208 ( 2023 ) 0 5 10 15 0 0. 5 ...
Chunk ID: 54, Page: 5, Text: , 0. 6435 ) fig. 4. two parameter diagrams prepared from the ldm showing the incoherent ( blue ), co...
Chunk ID: 55, Page: 5, Text: the solid magenta curves represent backward transition or sn points. the black curves respectively r...
Chunk ID: 56, Page: 5, Text: three different parts, namely incoherent ( blue ), coherent ( maroon ), and bistable ( gray ). note ...
Chunk ID: 57, Page: 5, Text: 2 ( b ) ]. as β is increased a little more, the system exhibits bistability. the numerically compute...
Chunk ID: 58, Page: 5, Text: . the bistable regime starts at the intersection point of the pitchfork line and the saddle node cur...
Chunk ID: 59, Page: 5, Text: , in summary, it is observed that k2 promotes bistability in the system. moreover, using the results...
Chunk ID: 60, Page: 5, Text: . note that ( = ) is analytically calculated from the ldm. in figs. 5 ( a ) and 5 ( b ) we ﬁx k2 to ...
Chunk ID: 61, Page: 5, Text: phase lag. this ﬁgure shows that numerical values ( black circles ) of both r and closely match with...
Chunk ID: 62, Page: 5, Text: i ) for ﬁxed k2, the system exhibits discontinuous transition to syn - chronization for low β with t...
Chunk ID: 63, Page: 5, Text: a ﬁxed k1. for lower β, transition is found to be continuous and the system exhibits discontinuous t...
Chunk ID: 64, Page: 5, Text: - ( d ) ] triadic coupling strength k2 for phase lag 0. 5. the solid and dashed lines ( red ) are ob...
Chunk ID: 65, Page: 6, Text: sangita dutta et al. physical review e 108, 034208 ( 2023 ) beyond a critical value. therefore, in t...
Chunk ID: 66, Page: 6, Text: of the ldm reveals the complex dependence of the transition scenario on the governing parameters. it...
Chunk ID: 67, Page: 6, Text: ldm show a very good agreement with numerical simulation results. acknowledgments s. d. acknowledges...
Chunk ID: 68, Page: 6, Text: j. kurths, and j. kurths, syn - chronization : a universal concept in nonlinear sciences ( cambridge...
Chunk ID: 69, Page: 6, Text: d. k. verma, p. parmananda, and s. boccaletti, phys. rev. e 91, 062909 ( 2015 ). [ 6 ] u. lee, m. ki...
Chunk ID: 70, Page: 6, Text: , international journal of bifurcation and chaos 10, 2361 ( 2000 ). [ 8 ] j. pantaleone, am. j. phys...
Chunk ID: 71, Page: 6, Text: j. buck, the quarterly review of biology 63, 265 ( 1988 ). [ 12 ] s. yamaguchi, h. isejima, t. matsu...
Chunk ID: 72, Page: 6, Text: ] f. dorﬂer and f. bullo, automatica 50, 1539 ( 2014 ). [ 15 ] j. l. van hemmen and w. f. wreszinski...
Chunk ID: 73, Page: 6, Text: ##211 ( 2005 ). [ 18 ] h. sakaguchi and y. kuramoto, prog. theor. phys. 76, 576 ( 1986 ). [ 19 ] o. ...
Chunk ID: 74, Page: 6, Text: ). [ 21 ] p. kundu and p. pal, chaos : an interdisciplinary journal of nonlinear science 29, 013123 ...
Chunk ID: 75, Page: 6, Text: , automatica 54, 114 ( 2015 ). [ 25 ] l. q. english, d. mertens, s. abdoulkary, c. b. fritz, k. skow...
Chunk ID: 76, Page: 6, Text: . bullo, siam j. control optim. 50, 1616 ( 2012 ). [ 28 ] e. omel ’ chenko and m. wolfrum, physica d...
Chunk ID: 77, Page: 6, Text: . rev. e 91, 010802 ( 2015 ). [ 31 ] p. s. skardal, d. taylor, and j. sun, phys. rev. lett. 113, 144...
Chunk ID: 78, Page: 6, Text: p. pal, epl ( europhysics letters ) 129, 30004 ( 2020 ). [ 34 ] p. khanra and p. pal, chaos, soliton...
Chunk ID: 79, Page: 6, Text: rev. e 83, 046221 ( 2011 ). [ 37 ] s. dutta, p. kundu, p. khanra, c. hens, and p. pal, phys. rev. e ...
Chunk ID: 80, Page: 6, Text: ##valenko, x. dai, k. alfaro - bittner, a. m. raigorodskii, m. perc, and s. boccaletti, phys. rev. l...
Chunk ID: 81, Page: 6, Text: . iacopini, v. latora, m. lucas, a. patania, j. - g. young, and g. petri, phys. rep. 874, 1 ( 2020 )...
Chunk ID: 82, Page: 6, Text: g. petri, a. barrat, and v. latora, nat. commun. 10, 1 ( 2019 ). [ 44 ] l. martignon, h. von hassein...
Chunk ID: 83, Page: 7, Text: impact of phase lag on synchronization in … physical review e 108, 034208 ( 2023 ) [ 45 ] s. yu, h. ...
Chunk ID: 84, Page: 7, Text: . 41, 1 ( 2016 ). [ 47 ] m. w. reimann, m. nolte, m. scolamiero, k. turner, r. perin, g. chindemi, p...
Chunk ID: 85, Page: 7, Text: ##101 ( 2011 ). [ 49 ] s. ghosh, p. khanra, p. kundu, p. ji, d. ghosh, and c. hens, chaos : an inter...
Chunk ID: 86, Page: 7, Text: ] a. e. sizemore, c. giusti, a. kahn, j. m. vettel, r. f. betzel, and d. s. bassett, j. comput. neur...
Chunk ID: 87, Page: 7, Text: , g. barabas, m. j. michalska - smith, and s. allesina, nature ( london ) 548, 210 ( 2017 ). [ 54 ] ...
Chunk ID: 88, Page: 7, Text: , 073101 ( 2022 ). [ 57 ] e. vasilyeva, a. kozlov, k. alfaro - bittner, d. musatov, a. raigorodskii,...
Chunk ID: 89, Page: 7, Text: 59 ] a. costa and m. farber, in conﬁguration spaces : geom - etry, topology and representation theor...
Chunk ID: 90, Page: 7, Text: . [ 62 ] y. zhang, v. latora, and a. e. motter, commun. phys. 4, 195 ( 2021 ). [ 63 ] c. bick, p. as...
Chunk ID: 91, Page: 7, Text: ##3193 ( 2021 ). [ 65 ] p. s. skardal and a. arenas, commun. phys. 3, 1 ( 2020 ). [ 66 ] p. rajwani,...
Chunk ID: 92, Page: 7, Text: govaerts, and y. a. kuznetsov, acm trans. math. softw. 29, 141 ( 2003 ). 034208 - 7...

In [84]:
chunk_lengths = []
for chunk in chunks:

    ids = tokenizer.encode(chunk["text"], 
                           add_special_toekns = False, 
                           truncation = False, 
                           verbose = False)
    chunk_lengths. append(len(ids))

print(f"chunk_lengths: {chunk_lengths}")
print(f"Max Chunk Length: {max(chunk_lengths)}")
print(f"Min chunk Length: {min(chunk_lengths)}")

chunk_lengths: [122, 124, 122, 122, 122, 121, 122, 122, 122, 122, 122, 22, 122, 125, 124, 124, 122, 124, 121, 122, 122, 122, 125, 122, 101, 122, 124, 122, 122, 120, 120, 122, 122, 122, 117, 118, 123, 61, 122, 123, 122, 121, 121, 122, 124, 124, 122, 122, 122, 122, 122, 122, 113, 122, 122, 122, 122, 122, 122, 121, 121, 122, 122, 122, 62, 122, 122, 122, 122, 122, 122, 122, 122, 123, 122, 122, 122, 122, 122, 122, 124, 122, 81, 122, 122, 123, 122, 122, 122, 122, 122, 123, 38]
Max Chunk Length: 125
Min chunk Length: 22

In [85]:
#chunk embedding 
chunk_texts = [chunk["text"] for chunk in chunks
               ]

print("Number of chunks:", len(chunk_texts))

Number of chunks: 93

In [86]:
#embedding 
embeddings = model.encode(chunk_texts, 
                convert_to_numpy=True,
                normalize_embeddings = True)

print(f"Embedding shape:", embeddings.shape)

Embedding shape: (93, 384)

In [87]:
#query verification
query = "Which equation determines the onset of continous transitions?"
query_embedding = model.encode(
    query,
    convert_to_numpy=True,
    normalize_embeddings=True
)

print(f"Query Embedding shape:", query_embedding.shape)

Query Embedding shape: (384,)

In [106]:
#function to accept a query 
#this accepts the query from the user and retrives answers 

def retrieve(query_embedding, k_top=3):

    #cosine similarity 
    scores = embeddings @ query_embedding

    #indices pf top k-scores 

    top_indices = np.argsort(scores)[::-1][:k_top]

    #results in a list 
    results = []
    for idx in top_indices:
        results.append(
            {"chunk_id": chunks[idx]["chunk_id"],
             "page": chunks[idx]["page"], 
             "text": chunks[idx]["text"], 
             "score": float(scores[idx])
             })   

    return results

In [107]:
#verification 
results = retrieve(query_embedding, k_top=3)

for result in results:
    print("="*80)
    print("Chunk_id:", result["chunk_id"])
    print()
    print(result["text"])
    print("Page:", result["page"])
    print("Similarity score:", result["score"])
    print()

================================================================================
Chunk_id: 46

point marking the onset of continuous transition, which gives k1 = k2. using it in the equation ( 13 ) the condition for the onset of continuous transition is obtained as k1 = k2 = 2 cos β. ( 14 ) now in particular, for ﬁxed k2 = 8, the onset of continuous transition occurs for k1 = 8 and β = cos−1 ( 1 / 4 ) = 1. 3181. in the numerical simulation, the continuous transition start also occurs exactly at this analytically determined value. on the other hand, for ﬁxed k1, as
Page: 4
Similarity score: 0.6300626397132874

================================================================================
Chunk_id: 66

of the ldm reveals the complex dependence of the transition scenario on the governing parameters. it is observed that the discontinuous transition is always as - sociated with a sn bifurcation. in the ﬁrst case mentioned above, the sn responsible for discontinuous transition is associated with a subcritical pitchfork bifurcation, while in the second case, sn bifurcation independently occur in a region of the parameter space. further, all the analyti - cally derived transition points determined from the ldm show a very good agreement with numerical simulation results.
Page: 6
Similarity score: 0.5350890755653381

================================================================================
Chunk_id: 43

creased starting from 0, the system moves from discontinuous to continuous transition states with the variation of k1. the discontinuous transition here is associated with the existence of the sn bifurcation point and it ceased to exist as the sn point meets the trivial ( r = 0 ) ﬁxed point. this observation helps to determine the starting point of continuous transition analytically. the equilibrium points of the ldm [ eq. ( 10 ) ] are given by r = 0 and r = k2 −k1 ± ( k1 + k2 ) 2 −
Page: 4
Similarity score: 0.533245861530304

In [108]:
#context 

def build_context(results):
    context_parts = []
    for result in results:
        context_parts.append(
            f"[Page{result['page']}\n"
            f"{result['text']}"
        )

    context = "\n\n".join(context_parts)
    return context

In [109]:
#context 
context = build_context(results)
print(context)

[Page4
point marking the onset of continuous transition, which gives k1 = k2. using it in the equation ( 13 ) the condition for the onset of continuous transition is obtained as k1 = k2 = 2 cos β. ( 14 ) now in particular, for ﬁxed k2 = 8, the onset of continuous transition occurs for k1 = 8 and β = cos−1 ( 1 / 4 ) = 1. 3181. in the numerical simulation, the continuous transition start also occurs exactly at this analytically determined value. on the other hand, for ﬁxed k1, as

[Page6
of the ldm reveals the complex dependence of the transition scenario on the governing parameters. it is observed that the discontinuous transition is always as - sociated with a sn bifurcation. in the ﬁrst case mentioned above, the sn responsible for discontinuous transition is associated with a subcritical pitchfork bifurcation, while in the second case, sn bifurcation independently occur in a region of the parameter space. further, all the analyti - cally derived transition points determined from the ldm show a very good agreement with numerical simulation results.

[Page4
creased starting from 0, the system moves from discontinuous to continuous transition states with the variation of k1. the discontinuous transition here is associated with the existence of the sn bifurcation point and it ceased to exist as the sn point meets the trivial ( r = 0 ) ﬁxed point. this observation helps to determine the starting point of continuous transition analytically. the equilibrium points of the ldm [ eq. ( 10 ) ] are given by r = 0 and r = k2 −k1 ± ( k1 + k2 ) 2 −

In [110]:
#building prompt 

def build_prompt(query, context):

    prompt = f""" You are a very helpful assistant. You are gievn the following context. if the context does not contain 
    enough inofrmation, say: "The provided context does not contain enough information".

    Use only the information provided in the context to answer the question.Please reframe from using external knowledge or making vague assumptions.

    Please refer to page number as well. 
    
    Context: {context}
    Question: {query}
    Answer: 
    """

    return prompt 

prompt = build_prompt(query, context)

In [111]:
#generator Ollama 

def generate_answer(prompt):

    resposne = ollama.chat(
        model = "qwen2.5:1.5b",
        messages = [
                    {
            "role": "user", 
            "content": prompt
        }
        ]
    )

    return resposne["message"]["content"]

#rag integrated with Ollama 
  
def rag(query, k_top=3):

    #Retrieve relevant chunks
    results = retrieve(
        query_embedding,
        k_top=k_top
    )

    #context
    context = build_context(results)

    #prompt
    prompt = build_prompt(
        query,
        context
    )

    #answer
    answer = generate_answer(prompt)

    return answer, results

In [112]:
query = "What is the condition for the saddle-node bifurcation?"

answer, results = rag(query)

print("Answer:")
print(answer)

Answer:
The condition for the onset of continuous transition is given as \( k1 = k2 = 2 \cos \beta \).

In [113]:
evaluation_data = [

    {
        "id": "Q01",
        "category": "factual",
        "question": "What network size was used in the numerical simulations?",
        "gold_answer": "N = 10^3",
        "gold_pages": [2],
        "answerable": True
    },

    {
        "id": "Q02",
        "category": "factual",
        "question": "What numerical integration method was used?",
        "gold_answer": "Fourth-order Runge-Kutta method",
        "gold_pages": [2],
        "answerable": True
    },

    {
        "id": "Q03",
        "category": "parameter",
        "question": "What time step was used in the simulations?",
        "gold_answer": "delta t = 0.01",
        "gold_pages": [2],
        "answerable": True
    },

    {
        "id": "Q04",
        "category": "parameter",
        "question": "What distribution was used for the natural frequencies?",
        "gold_answer": "A Lorentzian distribution",
        "gold_pages": [2],
        "answerable": True
    },

    {
        "id": "Q05",
        "category": "parameter",
        "question": "What are K1 and K2 in the model?",
        "gold_answer": "K1 is the pairwise coupling strength and K2 is the higher-order interaction coupling strength.",
        "gold_pages": [2],
        "answerable": True
    },

    {
        "id": "Q06",
        "category": "numerical",
        "question": "What range of K1 was used for forward continuation?",
        "gold_answer": "K1 was increased from -1 to 12.",
        "gold_pages": [2],
        "answerable": True
    },

    {
        "id": "Q07",
        "category": "conceptual",
        "question": "For fixed K2 = 8, what happens to the synchronization transition as phase lag beta increases?",
        "gold_answer": "The discontinuous transition becomes continuous as beta increases, with continuous transition above approximately beta = 1.318.",
        "gold_pages": [2, 4],
        "answerable": True
    },

    {
        "id": "Q08",
        "category": "conceptual",
        "question": "What happens when K2 is varied at fixed K1 = 2.5 as beta increases?",
        "gold_answer": "For small beta the transition is continuous, while for beta greater than about 0.6435 discontinuous transitions appear.",
        "gold_pages": [3, 4, 5],
        "answerable": True
    },

    {
        "id": "Q09",
        "category": "equation",
        "question": "What condition determines the saddle-node bifurcation?",
        "gold_answer": "(K1 + K2)^2 cos(beta) = 8 K2",
        "gold_pages": [4],
        "answerable": True
    },

    {
        "id": "Q10",
        "category": "equation",
        "question": "What condition determines the onset of continuous transition?",
        "gold_answer": "K1 = K2 = 2/cos(beta)",
        "gold_pages": [4],
        "answerable": True
    },

    {
        "id": "Q11",
        "category": "analytical",
        "question": "What critical phase lag is obtained for K2 = 8 at the onset of continuous transition?",
        "gold_answer": "beta = arccos(1/4) approximately 1.3181",
        "gold_pages": [4],
        "answerable": True
    },

    {
        "id": "Q12",
        "category": "analytical",
        "question": "What role does the saddle-node bifurcation play in the discontinuous transition?",
        "gold_answer": "The discontinuous transition is associated with the existence of a saddle-node bifurcation.",
        "gold_pages": [4, 6],
        "answerable": True
    },

    {
        "id": "Q13",
        "category": "conceptual",
        "question": "What is the main surprising effect of higher-order interactions on phase frustration?",
        "gold_answer": "In the presence of higher-order interactions, sufficiently large phase lag can promote discontinuous synchronization rather than suppress it.",
        "gold_pages": [3, 5, 6],
        "answerable": True
    },

    {
        "id": "Q14",
        "category": "unanswerable",
        "question": "What machine learning optimizer was used to train the model?",
        "gold_answer": None,
        "gold_pages": [],
        "answerable": False
    },

    {
        "id": "Q15",
        "category": "unanswerable",
        "question": "What GPU model was used for the numerical simulations?",
        "gold_answer": None,
        "gold_pages": [],
        "answerable": False
    }
]

In [114]:
for item in evaluation_data:
    print(
        item["id"],
        "gold_pages =", item["gold_pages"],
        "type =", type(item["gold_pages"]),
        "answerable =", item["answerable"]
    )

Q01 gold_pages = [2] type = <class 'list'> answerable = True
Q02 gold_pages = [2] type = <class 'list'> answerable = True
Q03 gold_pages = [2] type = <class 'list'> answerable = True
Q04 gold_pages = [2] type = <class 'list'> answerable = True
Q05 gold_pages = [2] type = <class 'list'> answerable = True
Q06 gold_pages = [2] type = <class 'list'> answerable = True
Q07 gold_pages = [2, 4] type = <class 'list'> answerable = True
Q08 gold_pages = [3, 4, 5] type = <class 'list'> answerable = True
Q09 gold_pages = [4] type = <class 'list'> answerable = True
Q10 gold_pages = [4] type = <class 'list'> answerable = True
Q11 gold_pages = [4] type = <class 'list'> answerable = True
Q12 gold_pages = [4, 6] type = <class 'list'> answerable = True
Q13 gold_pages = [3, 5, 6] type = <class 'list'> answerable = True
Q14 gold_pages = [] type = <class 'list'> answerable = False
Q15 gold_pages = [] type = <class 'list'> answerable = False

In [115]:
test_question = evaluation_data[0]["question"]

test_embedding = model.encode(
    test_question,
    convert_to_numpy=True,
    normalize_embeddings=True
)

test_results = retrieve(
    test_embedding,
    k_top=5
)

print(type(test_results))
print(test_results)

<class 'list'>
[{'chunk_id': 18, 'page': 2, 'text': '67 ]. ii. model description and numerical simuations the dynamics of a phase frustrated undirected simplicial complex of n number of nodes with global connectivity is governed by the following system of equations : = ωi + k1 n n j = 1 sin ( θj −θi −β ) + k2 n2 n j = 1 n l = 1 sin ( 2θj −θl −θi −β ), i = 1, 2,..., n. ( 3 ) this is the generalization of the classical sakaguchi -', 'score': 0.43347904086112976}, {'chunk_id': 3, 'page': 1, 'text': ', phase frustration can promote explosive synchronization in a network. a low - dimensional model of the network in the thermodynamic limit is derived using the ott - antonsen ansatz to explain this surprising result. analytical treatment of the low - dimensional model, including bifurcation analysis, explains the apparent counter intuitive result quite clearly. doi : 10. 1103 / physreve. 108. 034208 i. introduction synchronization [ 1 – 3 ] is a captivating phenomenon ob - served in natural and artiﬁcial systems [ 4', 'score': 0.35789597034454346}, {'chunk_id': 26, 'page': 3, 'text': '##le of the global network for different phase - lag values. forward and backward transitions are indicated by up and down arrows, respectively. ( a ) r is shown as a function of k1 for ﬁxed k2 = 8. ( b ) for ﬁxed k1 = 2. 5, r is plotted as a function of k2 for various β. next, to understand the impact of hoi coupling strength k2 on the synchronization transition, we simulate the system ( 3 ) by varying k2 with ﬁxed k1 = 2. 5 for different β. the variation', 'score': 0.34839850664138794}, {'chunk_id': 67, 'page': 6, 'text': 'ldm show a very good agreement with numerical simulation results. acknowledgments s. d. acknowledges the support from dst, india under the inspire program ( code no. if190605 ). c. h. is supported under inspire - faculty grant ( code no. ifa17 - ph193 ). [ 1 ] s. strogatz, sync : the emerging science of spontaneous order ( penguin uk, 2004 ). [ 2 ] a. pikovsky, m. rosenblum, j. kurths, and j. kurths, syn', 'score': 0.34289756417274475}, {'chunk_id': 91, 'page': 7, 'text': '##3193 ( 2021 ). [ 65 ] p. s. skardal and a. arenas, commun. phys. 3, 1 ( 2020 ). [ 66 ] p. rajwani, a. suman, and s. jalan, arxiv : 2302. 12076. [ 67 ] e. ott and t. m. antonsen, chaos : an interdisciplinary journal of nonlinear science 18, 037113 ( 2008 ). [ 68 ] a. dhooge, w. govaerts, and y. a. kuznets', 'score': 0.3356035351753235}]

In [116]:
def evaluate_retrieval(evaluation_data, k_max=5):

    retrieval_records = []

    for item in evaluation_data:

        # Skip unanswerable questions for retrieval evaluation
        if not item["answerable"]:
            continue

        question = item["question"]
        gold_pages = item["gold_pages"]

        #query embeding 
        query_embedding = model.encode(
            question,
            convert_to_numpy=True,
            normalize_embeddings=True
        )

        # Retrieve top-k chunks
        results = retrieve(
            query_embedding,
            k_top=k_max
        )

        # Pages returned by the retriever
        retrieved_pages = [
            result["page"]
            for result in results
        ]

        # Find rank of first relevant result
        first_relevant_rank = None

        for rank, result in enumerate(results, start=1):

            if result["page"] in gold_pages:
                first_relevant_rank = rank
                break

        #Hit@1
        hit_at_1 = int(
            any(
                page in gold_pages
                for page in retrieved_pages[:1]
            )
        )

        #Hit@3
        hit_at_3 = int(
            any(
                page in gold_pages
                for page in retrieved_pages[:3]
            )
        )

        #hit at 5
        hit_at_5 = int(
            any(
                page in gold_pages
                for page in retrieved_pages[:5]
            )
        )

        #reciprocal rank
        if first_relevant_rank is None:
            reciprocal_rank = 0.0
        else:
            reciprocal_rank = 1 / first_relevant_rank

        # Store results
        retrieval_records.append({
            "id": item["id"],
            "category": item["category"],
            "question": question,
            "gold_pages": gold_pages,
            "retrieved_pages": retrieved_pages,
            "first_relevant_rank": first_relevant_rank,
            "hit_at_1": hit_at_1,
            "hit_at_3": hit_at_3,
            "hit_at_5": hit_at_5,
            "reciprocal_rank": reciprocal_rank
        })

    return retrieval_records

In [117]:
retrieval_records = evaluate_retrieval(
    evaluation_data,
    k_max=5
)

print(type(retrieval_records))
print(len(retrieval_records))

<class 'list'>
13

In [118]:
retrieval_records[0]

{'id': 'Q01',
 'category': 'factual',
 'question': 'What network size was used in the numerical simulations?',
 'gold_pages': [2],
 'retrieved_pages': [2, 1, 3, 6, 7],
 'first_relevant_rank': 1,
 'hit_at_1': 1,
 'hit_at_3': 1,
 'hit_at_5': 1,
 'reciprocal_rank': 1.0}

In [119]:
#converting the records into dataframe  
retrieval_df = pd.DataFrame(retrieval_records)
print(retrieval_df)

     id    category                                           question  \
0   Q01     factual  What network size was used in the numerical si...
1   Q02     factual        What numerical integration method was used?
2   Q03   parameter        What time step was used in the simulations?
3   Q04   parameter  What distribution was used for the natural fre...
4   Q05   parameter                   What are K1 and K2 in the model?
5   Q06   numerical  What range of K1 was used for forward continua...
6   Q07  conceptual  For fixed K2 = 8, what happens to the synchron...
7   Q08  conceptual  What happens when K2 is varied at fixed K1 = 2...
8   Q09    equation  What condition determines the saddle-node bifu...
9   Q10    equation  What condition determines the onset of continu...
10  Q11  analytical  What critical phase lag is obtained for K2 = 8...
11  Q12  analytical  What role does the saddle-node bifurcation pla...
12  Q13  conceptual  What is the main surprising effect of higher-o...

   gold_pages  retrieved_pages  first_relevant_rank  hit_at_1  hit_at_3  \
0         [2]  [2, 1, 3, 6, 7]                  1.0         1         1
1         [2]  [4, 3, 6, 4, 3]                  NaN         0         0
2         [2]  [6, 4, 2, 2, 2]                  3.0         0         1
3         [2]  [1, 1, 3, 1, 2]                  5.0         0         0
4         [2]  [5, 1, 2, 5, 3]                  3.0         0         1
5         [2]  [2, 4, 5, 3, 5]                  1.0         1         1
6      [2, 4]  [5, 3, 5, 1, 3]                  NaN         0         0
7   [3, 4, 5]  [4, 3, 5, 2, 5]                  1.0         1         1
8         [4]  [4, 3, 6, 4, 5]                  1.0         1         1
9         [4]  [4, 6, 3, 4, 3]                  1.0         1         1
10        [4]  [4, 5, 5, 5, 3]                  1.0         1         1
11     [4, 6]  [6, 6, 4, 4, 4]                  1.0         1         1
12  [3, 5, 6]  [2, 1, 1, 3, 1]                  4.0         0         0

    hit_at_5  reciprocal_rank
0          1         1.000000
1          0         0.000000
2          1         0.333333
3          1         0.200000
4          1         0.333333
5          1         1.000000
6          0         0.000000
7          1         1.000000
8          1         1.000000
9          1         1.000000
10         1         1.000000
11         1         1.000000
12         1         0.250000

In [121]:
#retireval metrices 
hit_at_1 = retrieval_df["hit_at_1"].mean()
hit_at_3 = retrieval_df["hit_at_3"].mean()
hit_at_5 = retrieval_df["hit_at_5"].mean()
mrr = retrieval_df["reciprocal_rank"].mean()

print(f"Hit@1 : {hit_at_1:.3f}")
print(f"Hit@3 : {hit_at_3:.3f}")
print(f"Hit@5 : {hit_at_5:.3f}")
print(f"MRR   : {mrr:.3f}")

Hit@1 : 0.538
Hit@3 : 0.692
Hit@5 : 0.846
MRR   : 0.624

In [123]:
#inspecting failures 
failed_retrievals = retrieval_df[
    retrieval_df["hit_at_3"] == 0
]

failed_retrievals[
    [
        "id",
        "category",
        "question",
        "gold_pages",
        "retrieved_pages"
    ]
]

,id,category,question,gold_pages,retrieved_pages
1,Q02,factual,What numerical integration method was used?,[2],"[4, 3, 6, 4, 3]"
3,Q04,parameter,What distribution was used for the natural fre...,[2],"[1, 1, 3, 1, 2]"
6,Q07,conceptual,"For fixed K2 = 8, what happens to the synchron...","[2, 4]","[5, 3, 5, 1, 3]"
12,Q13,conceptual,What is the main surprising effect of higher-o...,"[3, 5, 6]","[2, 1, 1, 3, 1]"

In [125]:
lower_rank_success = retrieval_df[
    (retrieval_df["hit_at_1"] == 0) &
    (retrieval_df["hit_at_3"] == 1)
]

lower_rank_success[
    [
        "id",
        "category",
        "question",
        "gold_pages",
        "retrieved_pages",
        "first_relevant_rank"
    ]
]

,id,category,question,gold_pages,retrieved_pages,first_relevant_rank
2,Q03,parameter,What time step was used in the simulations?,[2],"[6, 4, 2, 2, 2]",3.0
4,Q05,parameter,What are K1 and K2 in the model?,[2],"[5, 1, 2, 5, 3]",3.0